### ISSUE TITLE
Inquiry about the Release of Code

### ISSUE THREAD

**Issue by Kedreamix** [JeongminB/E-D3DGS#3]
I noticed in the README that the paper and code were supposed to be updated around the 15th of July. Could you please let us know if there has been any progress on this? We are eagerly awaiting the release.

Thank you for your hard work!

**Comment by seoha-kim** [comment]
We just finished the camera-ready version last Thursday.
Now, we are going to update the project page and release the code.
Our goal is to do so by the end of July.

However, it may be slightly delayed because we are organizing the code along with other studies simultaneously.
I will update this on GitHub.

Thank you for your interest. 🙂

**Comment by seoha-kim** [comment]
The code is released.
We have been working on several research projects simultaneously, 
so it's taken us a bit longer to release the code. 
Thanks so much for your interest. 🙏🏻
